name: sounds
version: 1.0.0-beta.7
homepage: https://github.com/bsutton/sounds
documentation: https://github.com/bsutton/sounds/wiki
description: Sounds provide a complete api and Widgets for audio playback and recording. Both iOS and Android are supported.
repository: https://github.com/bsutton/sounds
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  device_info: ^2.0.0
  flutter_spinkit: ^5.0.0
  meta: ^1.3.0
  path: ^1.8.0
  path_provider: ^2.0.1
  provider: ^5.0.0
  sounds_common: ^1.0.8
  uuid: ^3.0.1
  flutter: 
    sdk: flutter
dev_dependencies: 
  dart_numerics: ^0.0.5
  pedantic: ^1.9.0
  effective_dart: ^1.2.1
  dshell: ^1.0.0
  lint: ^1.1.1
  pub_semver: ^1.4.4
  flutter_test: 
    sdk: flutter
dependency_overrides:
  # 5/3/21 Breaking changes due to Flutter 2 upgrade
  uuid: ^3.0.1
flutter: 
  plugin: 
    platforms: 
      android: 
        package: com.bsutton.sounds
        pluginClass: Sounds
      ios: 
        pluginClass: Sounds
