name: sounds
version: 1.0.0-beta.7
homepage: https://github.com/bsutton/sounds
documentation: https://github.com/bsutton/sounds/wiki
description: Sounds provide a complete api and Widgets for audio playback and recording. Both iOS and Android are supported.
repository: https://github.com/bsutton/sounds
environment: 
  sdk: ">=2.13.0 <3.0.0"
  flutter: '>=2.0.0 <3.0.0'
dependencies: 
  device_info_plus: ^2.0.1
  flutter_spinkit: ^5.0.0
  meta: ^1.1.8
  path: ^1.6.4
  path_provider: ^2.0.2
  provider: ^5.0.0
  sounds_common: ^1.0.6
  uuid: ^3.0.4
  flutter: 
    sdk: flutter
dev_dependencies: 
  dart_numerics: ^0.0.5
  pedantic: ^1.9.0
  effective_dart: ^1.2.1
  dshell: ^1.0.0
  e2e: ^0.5.0
  lint: ^1.1.1
  pub_semver: ^1.4.4
  flutter_test: 
    sdk: flutter
  flutter_driver: 
    sdk: flutter
dependency_overrides:
  crypto: ^3.0.0
  intl: ^0.17.0
  sounds_common:
    path: ../sounds_common
flutter: 
  plugin: 
    platforms: 
      android: 
        package: com.bsutton.sounds
        pluginClass: Sounds
      ios: 
        pluginClass: Sounds
